service: chat-gpt

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  # Add IAM policy to grant Lambda function access to DynamoDB
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:BatchGetItem
          Resource: "*"

resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: my-table

functions:
  get-data:
    handler: src/get-data.handler
    events:
      - http:
          path: get-data
          method: get
